web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('meet/', views.meet, name="meet"),
    path('post/<slug:slug>', views.post, name="post"),
    path('profile/', views.profile, name="profile"),
    path('create_post/', views.createPost, name="create_post"),
    path('update_post/<slug:slug>/', views.updatePost, name="update_post"),
    path('delete_post/<slug:slug>/', views.deletePost, name="delete_post"),
    path('send_email/', views.sendEmail, name="send_email"),
    path('send-meet/', views.sendMeet, name="send-meet"),
]

webnathan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path("ckeditor/", include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null = True, blank = True, upload_to="images", default="/images/placeholder.png")
    body = RichTextUploadingField(null = True, blank = True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):

        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count) 
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        super().save(*args, **kwargs)

web/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .models import Post
from .form import PostForm
from .filters import PostFilter
# Create your views here.

def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:3]

    context = {'posts':posts}
    return render(request, 'web/index.html', context)

def meet(request):
    return render(request, 'web/meet.html')

def posts(request):
    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs

    page = request.GET.get('page')
    paginator = Paginator(posts, 3)

    try: 
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    context = {'posts':posts, 'myFilter':myFilter}
    return render(request, 'web/posts.html', context)

def post(request, slug):
    post = Post.objects.get(slug=slug)

    context = {'post':post}
    return render(request, 'web/post.html', context)

def profile(request):
    return render(request, 'web/profile.html')

#CRUD_VIEW

@login_required(login_url="home")
def createPost(request):
    form = PostForm()
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context = {'form':form}
    return render(request, 'web/post_form.html', context)

@login_required(login_url="home")
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context = {'form':form}
    return render(request, 'web/post_form.html', context)

@login_required(login_url="home")
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)
    
    if request.method == 'POST':
        post.delete()
        return redirect('posts')

    context = {'item':post}
    return render(request, 'web/delete.html', context)

def sendEmail(request):

        if request.method == 'POST':

                template = render_to_string('web/email_template.html', {
                        'name':request.POST['name'],
                        'email':request.POST['email'],
                        'message':request.POST['message'],
                        })

                email = EmailMessage(
                        request.POST['subject'],
                        template,
                        settings.EMAIL_HOST_USER,
                        ['launathiel@gmail.com']
                        )

                email.fail_silently=False
                email.send()

        return render(request, 'web/send_email.html')

def sendMeet(request):

        if request.method == 'POST':

                template = render_to_string('web/email_template.html', {
                        'name':request.POST['name'],
                        'email':request.POST['email'],
                        'message':request.POST['message'],
                        })

                email = EmailMessage(
                        request.POST['subject'],
                        template,
                        settings.EMAIL_HOST_USER,
                        ['launathiel@gmail.com']
                        )

                email.fail_silently=False
                email.send()

        return render(request, 'web/send-meet.html')

web/templates/web/delete.html
{% extends 'web/main-nofooter.html' %}
{% load static %}
{% block content %}
<div class ="main-container">
    <br>
    <h3>Are you sure to delete this post?</h3>
    <br>
    <form action ="" method="POST" enctype="">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
</div>
{% endblock content %}

web/templates/web/email_template.html
{{message}}

{{name}}

{{email}}

web/templates/web/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Nathan's site</title>
	<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>


	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hello from Nathaniel!</h1>
			</div>


			<div class="intro-wrapper">
				{% include 'web/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/imageawal.png' %}">
					<h5 style="text-align: center;line-height: 0;">Choose yours!</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="dark" id="dark-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
						<div data-mode="red" style="background-color: #8E1533;" class="theme-dot"></div>
						<div data-mode="pastel" style="background-color: #ffd898;" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved <br>for your next vist</p>
				</div>

				<div class="right-column">

					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p>Learn, explore new things, and enjoy life.</p>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>About Me</h4>

					<p>I am a dreamer who always dreams at night. Now get addicted to the latest technology and never stop study about it.</p>

					<p>I have an interest in coding, cloud, development, operations, music, trading, and many more!

					<hr>

					<h4>Expertise</h4>

					<p>Collage student with primary focus on Cloud Native, Web & Mobile Development, and Cybersecurity. 
					
					<hr>
					
					<h4>My Resume</h4>
						<a target="_blank" href="{% static 'CV.pdf' %}">Download Resume</a></p>
					

					<h4>Skills and Concern</h4>
					<div id="skills">
						<ul>
							<li>Linux</li>
							<li>Docker</li>
							<li>Kubernetes</li>
							<li>Openstack</li>
							<li>Ansible</li>
							<li>GCP</li>
							<li>AWS</li>
						</ul>

						<ul>
							<li>C Programming</li>
							<li>Javascript</li>
							<li>Pyhon</li>
							<li>Java</li>
							<li>React Native</li>
							<li>Azure</li>
							<li>Gitlab</li>
						</ul>

					</div>
				</div>

				
				<div class="social-links">
					<img id="social_img" src="{% static 'images/cover.jpg' %}">
					<h3 style="margin-top: 30px;">Contact Me</h3>
					<div class="row" style="margin-left: 22px; margin-top: -10px;">
						<a target="_blank" href="https://t.me/launathiel"> 
							<i class="fab fa-telegram" style="font-size:32px; color:var(--mainText)"></i> 
						</a>
						<a target="_blank" href="https://www.linkedin.com/in/laurentius-nathaniel-845b27169/"> 
							<i class="fab fa-linkedin" style="font-size:32px; color:var(--mainText)"></i> 
						</a>
						<a target="_blank" href="https://www.instagram.com/launathiel/"> 
							<i class="fab fa-instagram" style="font-size:32px; color:var(--mainText)"></i> 
						</a>
						<a target="_blank" href="https://www.twitter.com/launathiel/"> 
							<i class="fab fa-twitter" style="font-size:32px; color:var(--mainText)"></i> 
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">My Blog</h3>

			<div class="post-wrapper">
				{% for post in posts %}
				<div>
					<div class="post">
						<img class="thumbnail" src="{{post.thumbnail.url}}">
						<div class="post-preview">
							<h6 class="post-title">{{post.headline}}</h6>
							<p class="post-intro">{{post.sub_headline}}</p>
							<a href="{% url 'post' post.slug %}">Read More</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

			<p align="center">
				<a href="{% url 'posts' %}">View More</a>
			</p>
		</div>
	</section>

	<section class="s2"">
		<div class="main-container" style="margin-bottom: 60px;">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}
				<a name="contact"></a>

				<label style="margin-left: -20px;">Name</label>
				<input required class="input-field" type="text" name="name">

				<label style="margin-left: 5px;">Subject</label>
				<input required class="input-field" type="text" name="subject">

				<label style="margin-left: 5px;">Email</label>
				<input required class="input-field" type="text" name="email">

				<label style="margin-left: 5px;">Message</label>
				<textarea required class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section> 

    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="menu_links">
                        <ul id="navigation" style="margin-bottom: -7px; margin-top: -10px; margin-left: 40px;">
                            <li><a href="{% url 'posts' %}">My Blog</a></li>
                            <li><a href="{% url 'meet' %}">Meet Me</a></li>
                            <li><a href="{% url 'home' %}#contact">Contact</a></li>
						</ul>
						<hr style="color: var(--borderColor); width: 400px;">
                    <div class="social_links" style="margin-top: 40px; margin-bottom: 35px;">
                        <ul>
							<a target="_blank" href="https://www.linkedin.com/in/laurentius-nathaniel-845b27169/"> 
								<i class="fab fa-linkedin" style="font-size:25px; color:var(--mainText)"></i> 
							</a>
							<a target="_blank" href="https://www.instagram.com/launathiel/"> 
								<i class="fab fa-instagram" style="font-size:25px; color:var(--mainText)"></i> 
							</a>
							<a target="_blank" href="https://www.twitter.com/launathiel/"> 
								<i class="fab fa-twitter" style="font-size:25px; color:var(--mainText)"></i> 
							</a>
							<a target="_blank" href="https://github.com/launathiel/"> 
								<i class="fab fa-github" style="font-size:25px; color:var(--mainText)"></i> 
							</a>
							<a target="_blank" href="https://gitlab.com/launathiel/"> 
								<i class="fab fa-gitlab" style="font-size:25px; color:var(--mainText)"></i> 
							</a>
							<a target="_blank" href="https://t.me/launathiel"> 
								<i class="fab fa-telegram" style="font-size:25px; color:var(--mainText)"></i> 
							</a>
                        </ul>
                    </div>
                    <div>
                        <p style="font-size: 12px; color: var(--secondaryText)">
						Created using django, template by dennisivy, created and modify by Laurentius Nathaniel
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

	<script type="text/javascript">
		let static = "{% static 'css' %}"
	</script>

	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

web/templates/web/main-nofooter.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Nathan's site</title>
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-47692315-56');
        </script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
        <link id="theme-style" rel="stylesheet" type="text/css" href="">
    </head>
    <body style="background-color: var(--secondaryColor);">

        {% include 'web/navbar.html' %}

        {% block content %}
        <!--content here-->
        {% endblock content %}
        
        <script type="text/javascript">
            let static = "{% static 'css' %}"
        </script>
    
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    </body>
</html>

web/templates/web/main.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Nathan's site</title>
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-47692315-56');
        </script>
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
        <link id="theme-style" rel="stylesheet" type="text/css" href="">
    </head>
    <body style="background-color: var(--secondaryColor);">

        {% include 'web/navbar.html' %}

        {% block content %}
        <!--content here-->
        {% endblock content %}

        <footer class="footer">
            <div class="footer_top">
                <div class="container">
                    <div class="row">
                        <div class="menu_links">
                            <ul id="navigation" style="margin-bottom: -7px; margin-top: -10px; margin-left: 40px;">
                                <li><a href="{% url 'posts' %}">My Blog</a></li>
                                <li><a href="{% url 'meet' %}">Meet Me</a></li>
                                <li><a href="{% url 'home' %}#contact">Contact</a></li>
                            </ul>
                            <hr style="color: var(--borderColor); width: 400px;">
                        <div class="social_links" style="margin-top: 40px; margin-bottom: 35px;">
                            <ul>
                                <a target="_blank" href="https://www.linkedin.com/in/laurentius-nathaniel-845b27169/"> 
                                    <i class="fab fa-linkedin" style="font-size:25px; color:var(--mainText)"></i> 
                                </a>
                                <a target="_blank" href="https://www.instagram.com/launathiel/"> 
                                    <i class="fab fa-instagram" style="font-size:25px; color:var(--mainText)"></i> 
                                </a>
                                <a target="_blank" href="https://www.twitter.com/launathiel/"> 
                                    <i class="fab fa-twitter" style="font-size:25px; color:var(--mainText)"></i> 
                                </a>
                                <a target="_blank" href="https://github.com/launathiel/"> 
                                    <i class="fab fa-github" style="font-size:25px; color:var(--mainText)"></i> 
                                </a>
                                <a target="_blank" href="https://gitlab.com/launathiel/"> 
                                    <i class="fab fa-gitlab" style="font-size:25px; color:var(--mainText)"></i> 
                                </a>
                                <a target="_blank" href="https://t.me/launathiel"> 
                                    <i class="fab fa-telegram" style="font-size:25px; color:var(--mainText)"></i> 
                                </a>
                            </ul>
                        </div>
                        <div>
                            <p style="font-size: 12px; color: var(--secondaryText)">
                            Created using django, template by dennisivy, created and modify by Laurentius Nathaniel
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        
        <script type="text/javascript">
            let static = "{% static 'css' %}"
        </script>
    
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    </body>
</html>

web/templates/web/meet.html
{% extends 'web/main-nofooter.html' %}

{% block content %}

<section class="s2"">
    <div class="main-container" style="margin-bottom: 60px;">
        <a href=""></a>
        <h1 style="text-align: center;">Meet Nathan</h1>
        <h6 style="text-align: center; margin-bottom: 30px;">meet.nathann.site</h6>

        <form id="contact-form" method="POST" action="{% url 'send-meet' %}">
            {% csrf_token %}
            <a name="contact"></a>

            <label style="margin-left: -20px;">Your Name</label>
            <input required class="input-field" type="text" name="name">

            <label style="margin-left: 5px;">Date and Time to Meet Me</label>
            <input required class="input-field" type="text" name="subject">

            <label style="margin-left: 5px;">Your Email</label>
            <input required class="input-field" type="text" name="email">

            <label style="margin-left: 5px;">Your Message</label>
            <textarea required class="input-field" name="message"></textarea>

            <input id="submit-btn" type="submit" value="Send">
        </form>
    </div>
</section> 

{% endblock content %}

web/templates/web/navbar.html
<div class="nav-wrapper">

	<!-- Link around dots-wrapper added after tutorial video -->
	<a href="{% url 'home' %}">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot"></div>
			<div id="dot-2" class="browser-dot"></div>
			<div id="dot-3" class="browser-dot"></div>
		</div>
	</a>
	

	<ul id="navigation">
		<li><a href="{% url 'posts' %}">My Blog</a></li>
		<li><a href="{% url 'meet'  %}">Meet Me</a></li>
		<li><a href="{% url 'home' %}#contact">Contact</a></li>
		{% if request.user.is_authenticated %}
			<li><a href="{% url 'create_post' %}">Create Post</a></li>
		{% endif %}
	</ul>
</div>

web/templates/web/post.html
{% extends 'web/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	img{
		max-width: 50%;
		object-fit: cover;
	}

	.featured_image{
		margin-top: 20px;
		margin-bottom: 20px;
	}
</style>

<div class="main-container" style="margin-bottom: 50px;">
	<div style="margin-top: 18px;">
		<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	</div>
	<div style="text-align: right; margin-bottom: 10px; margin-top: -22px">
		{% for tag in post.tags.all %}
			<span class="tag">{{tag}}</span>
		{% endfor %}
	</div>
	<hr>
	<h1>{{post.headline}}</h1>
	<img class="featured_image" src="{{post.thumbnail.url}}">
	<h4>{{post.sub_headline}}</h4>
	<br>
	<p>{{post.body|safe}}</p>
</div>

{% endblock content %}

web/templates/web/post_form.html
{% extends 'web/main-nofooter.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
    #div_id_tags > div{
            max-height: 100px;
            overflow-y: scroll;
            border:1px solid #888;
            padding: 5px;
            border-radius: 5px;
    }
</style>

<div class ="main-container">
    <h3>Create a Post</h3>

    <form action ="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Submit Post">
    </form>
    <br>
    <br>
</div>
{% endblock content %}

web/templates/web/posts.html
{% extends 'web/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 92px;
		border-radius: 5px;
		padding: 5px;
		border:1px solid var(--borderColor);
	}
</style>



<div class="main-container" style="margin-bottom: 30px;">
	<h1 style="text-align:center">Nathan's Posts</h1>

	<form id="searchForm" method="GET">
		{{myFilter.form|crispy}}
		<input class="btn btn-primary" type="submit" value="search">
	</form>

	<hr style="border:1.5px solid var(--borderColor);">

	<div class="post-wrapper">

		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">
					<h5 class="post-title">{{post.headline}}</h5>
					<p class="post-intro">{{post.sub_headline}}</p>
					<a href="{% url 'post' post.slug %}">Read More</a>

					{% if request.user.is_authenticated %}
					<a href="{% url 'update_post' post.slug %}">Edit</a>
					<a href="{% url 'delete_post' post.slug %}">Delete</a>
					{% endif %}

					<hr style="height:1px; border:none; color:rgb(126, 118, 118); background-color:rgb(212, 202, 202);">
					{% for tag in post.tags.all %}
						<span class="tag">{{tag}}</span>
					{% endfor %}
					<hr style="height:1px; border:none; color:rgb(126, 118, 118); background-color:rgb(212, 202, 202);">
				</div>
			</div>
		</div>
		{% empty %}
			<h3>No posts found...</h3>
		{% endfor %}
	</div>
	
	<div class="row">
		
		{% if posts.has_other_pages %}

			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link" style="background-color:var(--primaryColor); color: var(--mainText);">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link" style="background-color:var(--primaryColor); color: var(--mainText);">First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link" style="background-color:var(--borderColor); color: var(--primaryText);">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link" style="background-color:var(--primaryColor); color: var(--mainText);">{{i}}</a></li>
					{% endif %}
					
				{% endfor %}


				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link" style="background-color:var(--primaryColor); color: var(--mainText);">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link" style="background-color:var(--primaryColor); color: var(--mainText);">&raquo</a></li>
				{% endif %}
			</ul>

		{% endif %}
	</div>
</div>

<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>	

{% endblock content %}